use strict;
use warnings;
use File::Path qw(make_path);

my $SRC_DIR = 'assets/sprites/raw';
my $OUT_DIR = 'lib/Display/sprites';
my $TOOL    = 'tools/convert_sprites.pl';

make_path($OUT_DIR) unless -d $OUT_DIR;

opendir(my $dh, $SRC_DIR) or die "Cannot open $SRC_DIR: $!";
my @files = sort grep { /\.c$/ && -f "$SRC_DIR/$_" } readdir($dh);
closedir $dh;

for my $file (@files) {
    my $path = "$SRC_DIR/$file";
    open(my $fh, "<", $path) or die "Cannot open $path: $!";
    my @raw = <$fh>;
    close $fh;

    my ($frames, $width, $height);
    for (@raw) {
        if (/FRAME_COUNT\s+(\d+)/)   { $frames = $1 }
        if (/FRAME_WIDTH\s+(\d+)/)   { $width  = $1 }
        if (/FRAME_HEIGHT\s+(\d+)/)  { $height = $1 }
    }
    die "Missing metadata in $file" unless $frames && $width && $height;

    my $total = $width * $height;

    my @pixels;
    for (@raw) {
        next unless /^\s*0x/;
        while (/(0x[0-9a-fA-F]+)/g) {
            push @pixels, hex($1);
        }
    }

    my $expected = $frames * $total;
    die "Expected $expected pixels in $file, got " . scalar(@pixels) if @pixels != $expected;

    (my $name = $file) =~ s/\.c$//;
    my $def_name = uc($name);
    $def_name =~ s/-/_/g;
    my $label = $name;
    $label =~ s/-/_/g;
    (my $var_name = $label) =~ s/^(.)/\l$1/;

    my $out_path = "$OUT_DIR/" . lc($name) . ".h";
    open(my $out, ">", $out_path) or die "Cannot write $out_path: $!";

    print $out "#pragma once\n";
    print $out "#include <stdint.h>\n";
    print $out "#include <pgmspace.h>\n";
    print $out "\n";
    print $out "// Sprite: $var_name\n";
    print $out "// Size:   ${width}x${height} pixels\n";
    print $out "// Frames: $frames\n";
    print $out "//\n";
    print $out "// Format: RGB565 - 16-bit colour for the M5StickC Plus 2 LCD.\n";
    print $out "//   Each uint16_t value encodes one pixel as: RRRRRGGGGGGBBBBB\n";
    print $out "//   5 bits red | 6 bits green | 5 bits blue\n";
    print $out "//\n";
    print $out "// Transparent colour key: 0x1FF8 (byte-swapped magenta 0xF81F).\n";
    print $out "//   Pixels with this value are skipped by the drawing code.\n";
    print $out "//   They let the screen background colour show through.\n";
    print $out "//   The value is pre-swapped to match the byte order of all other\n";
    print $out "//   pixels in this array (see byte-swap note in the converter tool).\n";
    print $out "//\n";
    print $out "// PROGMEM: marks this array for storage in ESP32 flash memory.\n";
    print $out "//   On ESP32, PROGMEM is equivalent to const - flash storage is\n";
    print $out "//   memory-mapped and arrays can be accessed with normal [] syntax.\n";
    print $out "//   It is included here as a clear signal that this data is read-only\n";
    print $out "//   and should not be copied into RAM.\n";
    print $out "//\n";
    print $out "// Generated by: $TOOL\n";
    print $out "\n";
    print $out "#define SPRITE_${def_name}_FRAME_COUNT  $frames\n";
    print $out "#define SPRITE_${def_name}_WIDTH        $width\n";
    print $out "#define SPRITE_${def_name}_HEIGHT       $height\n";
    print $out "\n";
    print $out "// Transparent colour key - pass this to pushImage() so it skips\n";
    print $out "// transparent pixels and lets the background show through.\n";
    print $out "// This is 0xF81F (magenta) with its two bytes pre-swapped to 0x1FF8,\n";
    print $out "// matching the byte order of all other pixel values in this array.\n";
    print $out "#ifndef SPRITE_TRANSPARENT_COLOR\n";
    print $out "#define SPRITE_TRANSPARENT_COLOR 0x1FF8\n";
    print $out "#endif\n";
    print $out "\n";
    print $out "static const uint16_t PROGMEM sprite_${var_name}[${frames}][${total}] = {\n";

    my $idx = 0;
    for my $f (0 .. $frames - 1) {
        print $out "{\n";
        for my $row (0 .. $height - 1) {
            print $out "    ";
            for my $col (0 .. $width - 1) {
                my $abgr = $pixels[$idx++];
                my $a = ($abgr >> 24) & 0xFF;
                my $b = ($abgr >> 16) & 0xFF;
                my $g = ($abgr >> 8) & 0xFF;
                my $r = $abgr & 0xFF;

                my $swapped;
                if ($a < 128) {
                    $swapped = 0x1FF8;
                } else {
                    my $r5 = ($r >> 3) & 0x1F;
                    my $g6 = ($g >> 2) & 0x3F;
                    my $b5 = ($b >> 3) & 0x1F;

                    if ($r5 == 0x1F && $g6 == 0x3E && $b5 == 0x01) {
                        $swapped = 0x1FF8;
                    } else {
                        my $rgb565 = ($r5 << 11) | ($g6 << 5) | $b5;
                        $swapped = (($rgb565 >> 8) | (($rgb565 & 0xFF) << 8)) & 0xFFFF;
                    }
                }

                my $is_last_pixel_in_frame = ($row == $height - 1 && $col == $width - 1);
                my $col_sep = ($col < $width - 1) ? ", " : ($is_last_pixel_in_frame ? "\n" : ", \n");
                printf $out "0x%04X%s", $swapped, $col_sep;
            }
        }
        print $out ($f < $frames - 1) ? "},\n" : "}\n";
    }
    print $out "};\n";
    close $out;
    print "Generated: $out_path\n";
}
